=== ChrisJohns-me/raw-apex-games/projects/raw-apex-games-app/src/configs/config.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "assumptions": {
            "type": "object",
            "properties": {
                "opponentShieldDefault": {
                    "type": "integer"
                },
                "opponentHealthDefault": {
                    "type": "integer"
                },
                "isRosterNullPlayerDisconnect": {
                    "type": "boolean"
                },
                "knockdownExpireTime": {
                    "type": "number"
                },
                "eliminationExpireTime": {
                    "type": "number"
                }
            },
            "required": [
                "opponentShieldDefault",
                "opponentHealthDefault",
                "isRosterNullPlayerDisconnect",
                "knockdownExpireTime",
                "eliminationExpireTime"
            ]
        },
        "common": {
            "type": "object",
            "properties": {
                "playerDeathHUDTimeout": {
                    "type": "integer"
                },
                "matchEndHUDTimeout": {
                    "type": "integer"
                }
            },
            "required": [
                "playerDeathHUDTimeout",
                "matchEndHUDTimeout"
            ]
        },
        "brFacts": {
            "type": "object",
            "properties": {
                "respawnBannerExpireTime": {
                    "type": "integer"
                },
                "maxUltimateCooldownTime": {
                    "type": "integer"
                },
                "maxSquadSize": {
                    "type": "integer"
                },
                "ringDamageTickRate": {
                    "type": "integer"
                },
                "rings": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "ringNumber": {
                                    "type": "number"
                                },
                                "startTimeSec": {
                                    "type": "number"
                                },
                                "endTimeSec": {
                                    "type": "number"
                                },
                                "damagePerTick": {
                                    "type": "number"
                                }
                            },
                            "required": [
                                "ringNumber",
                                "startTimeSec",
                                "endTimeSec",
                                "damagePerTick"
                            ]
                        }
                    ]
                }
            },
            "required": [
                "respawnBannerExpireTime",
                "maxUltimateCooldownTime",
                "maxSquadSize",
                "ringDamageTickRate",
                "rings"
            ]
        },
        "facts": {
            "type": "object",
            "properties": {
                "maxShield": {
                    "type": "integer"
                },
                "maxHealth": {
                    "type": "integer"
                }
            },
            "required": [
                "maxShield",
                "maxHealth"
            ]
        },
        "featureFlags": {
            "type": "object",
            "properties": {
                "enableMatchTimerWindow": {
                    "type": "boolean"
                },
                "enableMiniInventoryWindow": {
                    "type": "boolean"
                },
                "enableMatchSummaryWindow": {
                    "type": "boolean"
                },
                "enableVideoCapture": {
                    "type": "boolean"
                }
            },
            "required": [
                "enableMatchTimerWindow",
                "enableMiniInventoryWindow",
                "enableMatchSummaryWindow"
            ]
        },
        "featureConfigs": {
            "type": "object",
            "properties": {},
            "required": []
        },
        "general": {
            "type": "object",
            "properties": {
                "enableMatchSummaryAd": {
                    "type": "boolean"
                }
            },
            "required": [
                "enableMatchSummaryAd"
            ]
        },
        "overwolfQuirks": {
            "type": "object"
        }
    },
    "required": [
        "assumptions",
        "common",
        "featureFlags",
        "facts",
        "general",
        "overwolfQuirks"
    ],
    "additionalProperties": false
}

=== ChrisJohns-me/raw-apex-games/projects/allfather-app/src/configs/config.prod.json
{
    "$schema": "./config.schema.json",
    "assumptions": {
        "opponentShieldDefault": 75,
        "opponentHealthDefault": 100,
        "isRosterNullPlayerDisconnect": true,
        "knockdownExpireTime": 10000,
        "eliminationExpireTime": 300000
    },
    "common": {
        "playerDeathHUDTimeout": 30000,
        "matchEndHUDTimeout": 15000
    },
    "brFacts": {
        "respawnBannerExpireTime": 60000,
        "maxUltimateCooldownTime": 360000,
        "maxSquadSize": 3,
        "ringDamageTickRate": 1500,
        "rings": [
            {
                "ringNumber": 1,
                "startTimeSec": 65,
                "endTimeSec": 680,
                "damagePerTick": 2
            },
            {
                "ringNumber": 2,
                "startTimeSec": 680,
                "endTimeSec": 895,
                "damagePerTick": 3
            },
            {
                "ringNumber": 3,
                "startTimeSec": 895,
                "endTimeSec": 1045,
                "damagePerTick": 10
            },
            {
                "ringNumber": 4,
                "startTimeSec": 1045,
                "endTimeSec": 1185,
                "damagePerTick": 20
            },
            {
                "ringNumber": 5,
                "startTimeSec": 1185,
                "endTimeSec": 13195,
                "damagePerTick": 20
            },
            {
                "ringNumber": 6,
                "startTimeSec": 13195,
                "endTimeSec": 9999,
                "damagePerTick": 25
            }
        ]
    },
    "facts": {
        "maxShield": 125,
        "maxHealth": 100
    },
    "featureFlags": {
        "enableMatchTimerWindow": true,
        "enableLegendSelectAssistWindow": true,
        "enableMiniInventoryWindow": true,
        "enableUltTimerWindow": true,
        "enableInflictionInsightWindow": true,
        "enableHealingHelperWindow": true,
        "enableReticleHelperWindow": false,
        "enableMatchSummaryWindow": true,
        "enableVideoCapture": false,
        "inflictionInsight": {
            "teamIndicatorUI": true,
            "visualizeDamageUI": true,
            "totalDamageAmount": true,
            "shieldDamageAmount": true,
            "healthDamageAmount": true,
            "platformUI": true,
            "showAssumedOpponentTeammateShields": false,
            "showAssumedOpponentTeammateHealth": false,
            "assumeKnockdownExpires": true,
            "assumeEliminationExpires": true
        },
        "legendSelectAssist": {
            "legendStats": true,
            "complimentaryLegends": true
        },
        "reticleHelper": {
            "aimingReticle": true
        }
    },
    "featureConfigs": {
        "inflictionInsight": {
            "damageResetTime": 20000
        },
        "legendSelectAssist": {
            "minLegendStatsMatches": 1,
            "maxComplimentaryLegends": 3,
            "minShowComplimentaryLegendsMatches": 100,
            "limitLegendStatsMatches": null,
            "limitComplimentaryLegendsMatches": 500,
            "complimentaryLegendsWeights": {
                "winWeight": 0.1,
                "placementWeight": 0.15,
                "damageWeight": 0.2,
                "eliminationWeight": 0.4,
                "deathWeight": 0.05,
                "assistWeight": 0.05,
                "knockdownWeight": 0.05,
                "durationWeight": 0
            },
            "legendRows": [
                {
                    "top": 26.15,
                    "right": 22.15,
                    "legendIds": [
                        "#character_bloodhound_NAME",
                        "#character_gibraltar_NAME",
                        "#character_lifeline_NAME",
                        "#character_pathfinder_NAME",
                        "#character_wraith_NAME"
                    ]
                },
                {
                    "top": 37.75,
                    "right": 14.7,
                    "legendIds": [
                        "#character_bangalore_NAME",
                        "#character_caustic_NAME",
                        "#character_mirage_NAME",
                        "#character_octane_NAME",
                        "#character_wattson_NAME",
                        "#character_crypto_NAME"
                    ]
                },
                {
                    "top": 49.37,
                    "right": 18.4,
                    "legendIds": [
                        "#character_revenant_NAME",
                        "#character_loba_NAME",
                        "#character_rampart_NAME",
                        "#character_horizon_NAME",
                        "#character_fuse_NAME"
                    ]
                },
                {
                    "top": 61,
                    "right": 22,
                    "legendIds": [
                        "#character_valkyrie_NAME",
                        "#character_seer_NAME",
                        "#character_ash_NAME",
                        "#character_maggie_NAME",
                        "#character_newcastle_NAME"
                    ]
                }
            ]
        },
        "ultTimer": {
            "maxHistoryCount": 5,
            "highConfidenceAmount": 0.7,
            "lowConfidenceAmount": 0.35
        }
    },
    "general": {
        "enableMatchSummaryAd": false
    },
    "overwolfQuirks": {}
}
